image: docker:latest

stages:
  - build
  - test
  - deploy

Build_and_Push:
  services:
  - docker:dind
  stage: build
  only:
    - schedules
#    - master
  tags:
    - docker

  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker info

  script: 
    # inject job name:
    - sed -i "s/<\/bo/<br>deployd by $CI_JOB_NAME<\/bo/g" app/app.js
    - docker build --pull --tag $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
#    - docker run $CI_REGISTRY_IMAGE /script/to/run/tests
#    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

Spin_Test_Environment:
  stage: test
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - >
      aws ec2 run-instances --image-id ami-0ded330691a314693 --count 1
      --instance-type t2.micro --key-name myec22
      --security-group-ids sg-01f96ce6a38acab33 --subnet-id subnet-752fd313
      --placement "{\"AvailabilityZone\": \"ap-southeast-2b\",\"Tenancy\": \"default\"}"

Deploy to Docker:
  stage: deploy
  only:
    - schedules
  tags:
    - docker
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'   
  script: 
    - ls -la 
    - >
      ssh ec2-user@$STAGING_SERVER "
      sudo docker stop my_app;
      sudo docker rm my_app;
      sudo docker pull  $CI_REGISTRY_IMAGE;
      sudo docker run -d -p 8888:3000 --name my_app $CI_REGISTRY_IMAGE"
      

Deploy to VM:
  artifacts:
    paths:
      - ./
  stage: deploy
  only:
    - schedules

  tags:
    - docker
    
  before_script:
    # Generates to connect to the AWS unit the SSH key.
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    # Sets the permission to 600 to prevent a problem with AWS
    # that it's too unprotected.
    - chmod 600  ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'   
  script: 
    - ls -la
    # inject job name:
    - sed -i "s/<\/bo/<br>deployd by $CI_JOB_NAME<\/bo/g" app/app.js
    - ssh ec2-user@$STAGING_SERVER "mkdir staging/_tmp && ls -la"
    - scp -r ./app/* ec2-user@$STAGING_SERVER:staging/_tmp
    - ssh ec2-user@$STAGING_SERVER "mv staging/live staging/_old && mv staging/_tmp staging/live"
    - ssh ec2-user@$STAGING_SERVER "rm -rf staging/_old  && cd staging/live && npm install && npm start"
  environment:     
    name: staging     
    # Exposes a button that when clicked take you to the defined URL:
    url: http://$STAGING_SERVER:8080/ 

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - export
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
    - master
